feat: add init command
callstack/ai-cli pull request #12
Opened 2024-02-21 12:42 UTC by Q1w1N

Adding new init command

### Summary

init command can be triggered manually, and it triggers automatically if prompt i run withour config file.

### Test plan

Run through all use cases.

2024-02-21 22:15 UTC, mdjastrzebski commented on src/commands/prompt/index.ts
> +  handler: (args) => {
Instead of trying to handle it here, you should modify `bin.ts` to include init command as well.

2024-02-21 22:17 UTC, mdjastrzebski commented on src/commands/init/index.ts
> +      message: 'Do you already have OpenAI API key?',
You are asking about OpenAI api key, what about case when user wanted to provide only Perplexity key?

2024-02-21 22:18 UTC, mdjastrzebski commented on src/commands/init/index.ts
> +      message: 'Paste your OpenAI key here:',
Ditto Perplexity key.

2024-02-21 22:23 UTC, mdjastrzebski requested changes
Looks promising. I've noticed some issue to be handled:
1. Prompt always ask for OpenAI key (message is fixed to OpenAI)
2. `init` command should be configured on `bin.ts` level, not inside `prompt.ts`
3. We currently have `~.airc` file which is a JSON file but without `.json` extension editors might not recognize it as such. 

In order to mitigate it for early adopters, let's a a simple code that runs early and moves `~.airc.json` file to `~/.airc.json`

```
const LEGACY_CONFIG_FILE = `.airc`;
const CONFIG_FILE = `.airc.json`;
```

2024-02-22 12:37 UTC, mdjastrzebski commented on src/commands/init/index.ts
> +  describe: 'initialize the AI Cli',
```suggestion
  describe: 'User-friendly config setup',
```

2024-02-22 12:38 UTC, mdjastrzebski commented on src/commands/init/init.ts
> +      message: 'Which inference provider would you like to set up:',
```suggestion
      message: 'Which inference provider would you like to use:',
```

2024-02-22 12:39 UTC, mdjastrzebski commented on src/commands/init/init.ts
> +    output.outputDefault(`You can get API key for ${provider.label} from here:`);
```suggestion
    output.outputDefault(`You can get your ${provider.label} API key here:`);
```

2024-02-22 12:41 UTC, mdjastrzebski commented on src/commands/init/init.ts
> +  output.outputBold('For one of questions ask the prompt as command params');
```suggestion
  output.outputBold('For a single question and answer just pass the prompt as param');
```

2024-02-22 12:41 UTC, mdjastrzebski commented on src/commands/init/init.ts
> +  output.outputBold('For interactive session use `-i` (or "--interactive") option. ');
```suggestion
  output.outputBold('For interactive session use "-i" (or "--interactive") option. ');
```

2024-02-22 12:42 UTC, mdjastrzebski commented on src/commands/init/init.ts
> +  output.outputBold("Or just start 'ai' without any parameters.");
```suggestion
  output.outputBold("or just start 'ai' without any params.");
```

2024-02-22 12:43 UTC, mdjastrzebski commented on src/config-file.ts
> +  if (fs.existsSync(legacyConfigPath)) {
```suggestion
  if (fs.existsSync(legacyConfigPath) && !fs.existsSync(configPath)) {
```

2024-02-22 12:44 UTC, mdjastrzebski commented on src/providers/index.ts
> +    throw new Error('No config file found.');
[nit] refactor to have an early throw instead of nested ifs

2024-02-22 12:44 UTC, mdjastrzebski commented on src/providers/index.ts
> +      throw new Error('No providers found in ~/.airc file.');
[nit] refactor to have an early throw instead of nested ifs

2024-02-22 12:46 UTC, mdjastrzebski approved these changes
Looks good!

Pls resolve comments before merging @Q1w1N.

2024-02-22 13:52 UTC, Q1w1N commented on src/commands/init/index.ts
> +  describe: 'initialize the AI Cli',
done

2024-02-22 13:52 UTC, Q1w1N commented on src/commands/init/init.ts
> +      message: 'Which inference provider would you like to set up:',
done

2024-02-22 13:52 UTC, Q1w1N commented on src/commands/init/init.ts
> +    output.outputDefault(`You can get API key for ${provider.label} from here:`);
Done

2024-02-22 13:53 UTC, Q1w1N commented on src/commands/init/init.ts
> +  output.outputBold('For one of questions ask the prompt as command params');
done

2024-02-22 13:53 UTC, Q1w1N commented on src/commands/init/init.ts
> +  output.outputBold('For interactive session use `-i` (or "--interactive") option. ');
done

2024-02-22 13:54 UTC, Q1w1N commented on src/commands/init/init.ts
> +  output.outputBold("Or just start 'ai' without any parameters.");
done

2024-02-22 13:54 UTC, Q1w1N commented on src/config-file.ts
> +  if (fs.existsSync(legacyConfigPath)) {
done

2024-02-22 13:56 UTC, Q1w1N commented on src/providers/index.ts
> +    throw new Error('No config file found.');
done

2024-02-22 13:56 UTC, Q1w1N commented on src/providers/index.ts
> +      throw new Error('No providers found in ~/.airc file.');
done

2024-02-22 14:46 UTC, merged